### PR TITLE
Gameplay improvements

### PR DESCRIPTION
**Pull request by BigETI**
- Ships do now shoot faster
- Player ships can now move on the X axis

### CODE REVIEW

**Comment by BigETI** [comment]
Forgot to add that the back button in Android or escape button in Windows now closes the game.

**Comment by AmirSavand** [comment]
I appropriate your effort but I can not accept this pull request.

- Ships fire rate gets upgraded so changing the base value is a bad idea.
- You should not change a projects code format when you're making a pull request, the current code format is Visual Studio's default code format for C#.
- Documentation for every variable is not required at all in this project, if a function needs detail then yes.

So all that said, I recommend you to make a pull request for existing [issues](https://github.com/AmirSavand/breakers-force/issues).
Also make sure to resolve *only* 1 issue in each pull.

Feel free to create an issue for the exit button (if not already created).

And again, thank you for your pull request.

**Comment by BigETI** [comment]
I understand why this pull request has been closed, but some points are questionable in my opinion:

- The modified files does were formatted `Ctrl+K+D` according to the standard code format option of Visuals Studio for C#
- I use the inbuild XML code documentation for good measure (and it is considered good practice to do) on any class, interface, enumerator, members, fields, properties, methods for automated code documentation tools.
- Just my opinion, but resolving each issue with one pull request might be acceptable for a small project, but for a large scale project that might get pretty spammy when you have hundreds of thousands features or bugs to patch.

**Comment by AmirSavand** [comment]
I agree that some projects can not have 1 issue fixed in 1 pull request but the current issues are pretty straightforward.

I also agree that the XML documentation is good practice but when you're contributing to a project you should follow the project code format and style which is no big deal since the reviewer can update the code to fit the project style.

**Pull request closed without merging**
